/*
 * generated by Xtext
 */
package de.wwu.pi.mdsd05.validation

import de.wwu.pi.mdsd05.group05DSL.Group05DSLPackage
import org.eclipse.xtext.validation.Check
import de.wwu.pi.mdsd05.group05DSL.Entitytype
import de.wwu.pi.mdsd05.group05DSL.Model
import org.eclipse.xtend.expression.Resource

//import org.eclipse.xtext.validation.Check

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class Group05DSLValidator extends AbstractGroup05DSLValidator {


	@Check
	def public void checkAbtractFeatures(Entitytype entitytype)
	{
		if(!isSuperClass(entitytype))
		{
			error("class has no superclass and may not be abstract", Group05DSLPackage.Literals.ENTITYTYPE__ABSTRACT);
		}
		
	}

	def public boolean isSuperClass(Entitytype entitytype)
	{
		var entitytypes = (entitytype.eContainer() as Model).getEntitytypes();
		for(Entitytype e: entitytypes){
			if(e.getSupertype().equals(entitytype)) return true;
		}	
		return false;
	}




//  public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					MyDslPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}
}
