/*
 * generated by Xtext
 */
package de.wwu.pi.mdsd05.validation


import de.wwu.pi.mdsd05.group05DSL.EntryWindow
import de.wwu.pi.mdsd05.group05DSL.UIElement
import de.wwu.pi.mdsd05.group05DSL.Group05DSLPackage
import org.eclipse.xtext.validation.Check
import de.wwu.pi.mdsd05.group05DSL.Entitytype
import de.wwu.pi.mdsd05.group05DSL.Reference
import de.wwu.pi.mdsd05.group05DSL.Multiplicity



import de.wwu.pi.mdsd05.group05DSL.Entitytype
import de.wwu.pi.mdsd05.group05DSL.EntryWindow
import de.wwu.pi.mdsd05.group05DSL.Field
import de.wwu.pi.mdsd05.group05DSL.Group05DSLPackage
import de.wwu.pi.mdsd05.group05DSL.Model
import de.wwu.pi.mdsd05.group05DSL.Property
import de.wwu.pi.mdsd05.group05DSL.UIElement
import java.util.ArrayList
import org.eclipse.xtext.validation.Check

import static extension de.wwu.pi.mdsd05.helper.HelperMethods.*
import de.wwu.pi.mdsd05.group05DSL.Attribute

import de.wwu.pi.mdsd05.group05DSL.Button
import de.wwu.pi.mdsd05.group05DSL.Inscription

import de.wwu.pi.mdsd05.group05DSL.ListWindow



//import org.eclipse.xtext.validation.Check

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class Group05DSLValidator extends AbstractGroup05DSLValidator {


	@Check
	def public void checkAbtractFeatures(Entitytype entitytype)
	{
		if(!isSuperClass(entitytype) && entitytype.abstract!=null)
		{
			error("class has no superclass and may not be abstract", Group05DSLPackage.Literals.ENTITYTYPE__ABSTRACT);
		}
		
	}

	def public boolean isSuperClass(Entitytype entitytype)
	{
		var entitytypes = (entitytype.eContainer() as Model).getEntitytypes();
		for(Entitytype e: entitytypes){
			if(e.getSupertype()!=null && e.getSupertype().equals(entitytype)) return true;
		}	
		return false;
	}


	@Check
	def checkWindowLimit(Entitytype entitytype) {
		val model = entitytype.eContainer as Model;
		
		var entryWindows = model.uiwindows.filter[it instanceof EntryWindow && it.entitytype == entitytype];
		var listWindows = model.uiwindows.filter[it instanceof ListWindow && it.entitytype == entitytype];
		if (entryWindows.size > 1) {
			error('Entitytype ' + entitytype.name + ' has more than one entry window.', entitytype, Group05DSLPackage.Literals.ENTITYTYPE__NAME)
		}
		if (listWindows.size > 1) {
			error('Entitytype ' + entitytype.name + ' has more than one list window.', entitytype, Group05DSLPackage.Literals.ENTITYTYPE__NAME)
		}
		
	}



@Check
def checkUIElementOverlapping(EntryWindow ewindow){
	
	for (element : ewindow.getElements()){
		for (element2 : ewindow.getElements()){
		if (!(element == element2) && overlapping(element, element2))
	
	warning(element + "and" + element2 + "overlap each other!", Group05DSLPackage.Literals.ENTRY_WINDOW__ELEMENTS);}}
}

@Check
def checkCyclicInheritance(Entitytype entity){
	if(cyclicInheritance(entity))
		error("Cyclic inheritance is not allowed", Group05DSLPackage.Literals.MODEL__ENTITYTYPES);
}

@Check
def checkReferences(Entitytype entity){
	if(fReference(entity))
		error(entity + "is not correctly referenced", Group05DSLPackage.Literals.MODEL__ENTITYTYPES)
}

def fReference(Entitytype entity){
	var Multiplicity mult;
	var Reference opRef;
	var Entitytype opEnt;
	for (ref : entity.getProperties().filter[re|re instanceof Reference].map[re| re as Reference]){
		
		mult = ref.multiplicity
		opEnt = ref.references
		opRef = opEnt.properties.filter[re|re instanceof Reference].map[re| re as Reference].filter[re|re.references == entity] as Reference
		if (opRef == null) return true
		if (mult == opRef.multiplicity) return true
//		if (opEnt == entity) return true
		
				}
	return true
}

def cyclicInheritance(Entitytype entity){

	var superclass = entity.getSupertype();
	while(true){
		if (superclass == null) return false;
		if (superclass == entity) return true;
		superclass = superclass.getSupertype();
		}
	return false

}

def overlapping(UIElement element, UIElement element2){
	val x1 = element.getPosition().getX();
	val y1 = element.getPosition().getY();
	val x2 = element2.getPosition().getX();
	val y2 = element2.getPosition().getY();
	val width1 = element.getSize().getWidth();
	val width2 = element2.getSize().getWidth();
	val height2 = element2.getSize().getHeight();
	val height1 = element.getSize().getHeight();

	if (x1 < x2 && (x1 + width1) > x2) return true
	if (x1 > x2 && (x2 + width2) > x1) return true
	if (y1 < y2 && (y1 + height1) > y2) return true
	if (y1 > y2 && (y2 + height2) > y1) return true
	return false
}
//  public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					MyDslPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}
 @Check
 def areAllPropertiesIncludedInTheEntrywindow(EntryWindow entryWindow){
 	val allProperties=entryWindow.entitytype.allPropertiesIncludingSuperproperties.filter[prop|!(prop instanceof Attribute)||(prop as Attribute).optional==null];
 	val fields= new ArrayList<Field>;
 	fields += entryWindow.elements.filter[elem|elem instanceof Field].map[elem|elem as Field];
 	for (Property property: allProperties){
 		if (!fields.map[field|field.property].contains(property)){
 			error("The property " + property.name + " has no corresponding field in the entryWindow " + entryWindow.name + ".", Group05DSLPackage.Literals.UI_WINDOW__NAME);
 		}
 	}
 }
<<<<<<< HEAD
  @Check
 def areAllOptionalPropertiesIncludedInTheEntrywindow(EntryWindow entryWindow){
 	val allProperties=entryWindow.entitytype.allPropertiesIncludingSuperproperties.filter[prop|(prop instanceof Attribute)&&(prop as Attribute).optional!=null];
 	val fields= new ArrayList<Field>;
 	fields += entryWindow.elements.filter[elem|elem instanceof Field].map[elem|elem as Field];
 	for (Property property: allProperties){
 		if (!fields.map[field|field.property].contains(property)){
 			warning("The optional property " + property.name + " has no corresponding field in the entryWindow " + entryWindow.name + ".", Group05DSLPackage.Literals.UI_WINDOW__NAME);
 		}
 	}
 }  
 @Check
 def isAPropertyImplementedMultipleTimesAsAField(Field field){
 	val entryWindow=field.eContainer as EntryWindow;
 	for (Field windowField:entryWindow.elements.filter[elem|elem instanceof Field && !elem.equals(field)].map[elem|elem as Field]){
 		if (windowField.property.equals(field.property))
 		 			warning("The property " + field.property.name + " is referenced in multiple Fields.", Group05DSLPackage.Literals.FIELD__PROPERTY);
 		
 	}
 	
 	}
 	
 }
=======
 
 @Check
 def missingCeateEditButton(EntryWindow window)
 {
 	var Boolean exists = false;
 
  	for(UIElement elem:  window.elements.filter[e|e instanceof Button])
 	{
 		var Button btn = elem as Button		
		if (btn.inscription.equals(Inscription.CREATE_EDIT))
		{
			exists = true;
		}
 	}
 	
 	if(!exists)
 	{
 		error ("EntryWindow requires Create/Edit Button", window.eContainer, window.eContainingFeature);
 	}
 
 }
 
}
>>>>>>> f5928ca168d0049512353bd7b997b25893a8563a
