/*
 * generated by Xtext
 */
package de.wwu.pi.mdsd05.validation

import de.wwu.pi.mdsd05.group05DSL.EntryWindow
import de.wwu.pi.mdsd05.group05DSL.UIElement
import de.wwu.pi.mdsd05.group05DSL.Group05DSLPackage
import org.eclipse.xtext.validation.Check

//import org.eclipse.xtext.validation.Check

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class Group05DSLValidator extends AbstractGroup05DSLValidator {

@Check
def checkUIElementOverlapping(EntryWindow ewindow){
	
	for (element : ewindow.getElements())
		for (element2 : ewindow.getElements())
		if (!(element == element2) && overlapping(element, element2))
	
	warning(element + "and" + element2 + "overlap each other!", Group05DSLPackage.Literals.ENTRY_WINDOW__ELEMENTS);
}

def overlapping(UIElement element, UIElement element2){
	val x1 = element.getPosition().getX();
	val y1 = element.getPosition().getY();
	val x2 = element2.getPosition().getX();
	val y2 = element2.getPosition().getY();
	val width1 = element.getSize().getWidth();
	val width2 = element2.getSize().getWidth();
	val height2 = element2.getSize().getHeight();
	val height1 = element.getSize().getHeight();

	if (x1 < x2 && (x1 + width1) > x2) return true
	if (x1 > x2 && (x2 + width2) > x1) return true
	if (y1 < y2 && (y1 + height1) > y2) return true
	if (y1 > y2 && (y2 + height2) > y1) return true
	return false
}
//  public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					MyDslPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}
}
