/*
 * generated by Xtext
 */
package de.wwu.pi.mdsd05.ui.contentassist

import de.wwu.pi.mdsd05.ui.contentassist.AbstractGroup05DSLProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class Group05DSLProposalProvider extends AbstractGroup05DSLProposalProvider {
}
