/*
 * generated by Xtext
 */
package de.wwu.pi.mdsd05;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class Group05DSLRuntimeModule extends de.wwu.pi.mdsd05.AbstractGroup05DSLRuntimeModule {

}
