/*
 * generated by Xtext
 */
package de.wwu.pi.mdsd05.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class Group05DSLUiModule extends de.wwu.pi.mdsd05.ui.AbstractGroup05DSLUiModule {
	public Group05DSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
